// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Homeschool.Data;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Homeschool.Data.Context
{
    public partial class HomeschoolContext
    {
        private HomeschoolContextProcedures _procedures;

        public virtual HomeschoolContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new HomeschoolContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public HomeschoolContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HsLessonQueue>().HasNoKey().ToView(null);
        }
    }

    public interface IHomeschoolContextProceduresContract
    {
        Task<List<HsLessonQueue>> usp_GetLessonQueueAsync(int? maxRequired, int? minRequired, CancellationToken cancellationToken = default);
    }

    public partial class HomeschoolContextProcedures
    {
        private readonly HomeschoolContext _context;

        public HomeschoolContextProcedures(HomeschoolContext context)
        {
            _context = context;
        }

        public virtual async Task<List<HsLessonQueue>> usp_GetLessonQueueAsync(int? maxRequired, int? minRequired, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "maxRequired",
                    Value = maxRequired ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "minRequired",
                    Value = minRequired ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<HsLessonQueue>("EXEC @returnValue = [dbo].[usp_GetLessonQueue] @maxRequired, @minRequired", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
