// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Homeschool.Data;
using Homeschool.Data.Context.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;

namespace Homeschool.Data.Context
{
    using Microsoft.Extensions.DependencyInjection;

    public partial class HomeschoolContext : DbContext
    {
        public static IServiceProvider ServiceProvider
        {
            get;
            private set;
        }

        public HomeschoolContext(IServiceProvider serviceProvider, DbContextOptions<HomeschoolContext> options)
            : base(options)
        {
            ServiceProvider = serviceProvider;
        }

        public virtual DbSet<HsChapter> HsChapters { get; set; } = null!;
        public virtual DbSet<HsCourse> HsCourses { get; set; } = null!;
        public virtual DbSet<HsGradebook> HsGradebooks { get; set; } = null!;
        public virtual DbSet<HsLesson> HsLessons { get; set; } = null!;
        public virtual DbSet<HsSubject> HsSubjects { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.HsChapterConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HsCourseConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HsGradebookConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HsLessonConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HsSubjectConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }

    public partial class HomeschoolContext
    {
        public static HomeschoolContext GetNewContext()
            => ServiceProvider?.GetRequiredService<HomeschoolContext>();
    }
}
