// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Homeschool.Data
{
    [Table("hs_course")]
    [Index(nameof(CourSubjUid), Name = "IX_hs_course_cour_subj_uid")]
    public partial class HsCourse
    {
        public HsCourse()
        {
            HsChapters = new HashSet<HsChapter>();
        }

        [Key]
        [Column("cour_uid")]
        public Guid CourUid { get; set; }
        [Column("cour_slug")]
        [StringLength(50)]
        public string CourSlug { get; set; } = null!;
        [Column("cour_title")]
        public string? CourTitle { get; set; }
        [Column("cour_desc")]
        public string? CourDesc { get; set; }
        [Column("cour_url")]
        public string? CourUrl { get; set; }
        [Column("cour_subj_uid")]
        public Guid? CourSubjUid { get; set; }
        [Column("cour_display_order", TypeName = "money")]
        public decimal CourDisplayOrder { get; set; }
        [Required]
        [Column("cour_enabled")]
        public bool? CourEnabled { get; set; }
        [Column("cour_icon")]
        [StringLength(50)]
        public string? CourIcon { get; set; }

        [ForeignKey(nameof(CourSubjUid))]
        [InverseProperty(nameof(HsSubject.HsCourses))]
        public virtual HsSubject? CourSubjU { get; set; }
        [InverseProperty(nameof(HsChapter.ChapCourU))]
        public virtual ICollection<HsChapter> HsChapters { get; set; }
    }
}