// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Homeschool.Data
{
    public partial class HsLessonQueue
    {
        public Guid course_uid { get; set; }
        public Guid chapter_uid { get; set; }
        public Guid lesson_uid { get; set; }
        public string course_icon { get; set; }
        public bool lesson_is_past_due { get; set; }
        public string course_title { get; set; }
        public string chapter_title { get; set; }
        public string lesson_title { get; set; }
        public string lesson_url { get; set; }
        public DateTime? lesson_marked_completed { get; set; }
        public DateTime? lesson_last_opened { get; set; }
    }
}
