// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Homeschool.Data
{
    [Table("hs_subject")]
    public partial class HsSubject
    {
        public HsSubject()
        {
            HsCourses = new HashSet<HsCourse>();
        }

        [Key]
        [Column("subj_uid")]
        public Guid SubjUid { get; set; }
        [Column("subj_name")]
        [StringLength(50)]
        public string SubjName { get; set; } = null!;
        [Column("subj_display_order", TypeName = "money")]
        public decimal SubjDisplayOrder { get; set; }

        [InverseProperty(nameof(HsCourse.CourSubjU))]
        public virtual ICollection<HsCourse> HsCourses { get; set; }
    }
}