// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Homeschool.Data;
using Homeschool.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Homeschool.Data.Context.Configurations
{
    public partial class HsChapterConfiguration : IEntityTypeConfiguration<HsChapter>
    {
        public void Configure(EntityTypeBuilder<HsChapter> entity)
        {
            entity.Property(e => e.ChapUid).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.ChapCourU)
                .WithMany(p => p.HsChapters)
                .HasForeignKey(d => d.ChapCourUid)
                .HasConstraintName("FK_hs_chapter_hs_course");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HsChapter> entity);
    }
}
