// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Homeschool.Data;
using Homeschool.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Homeschool.Data.Context.Configurations
{
    public partial class HsCourseConfiguration : IEntityTypeConfiguration<HsCourse>
    {
        public void Configure(EntityTypeBuilder<HsCourse> entity)
        {
            entity.Property(e => e.CourUid).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CourEnabled).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.CourSubjU)
                .WithMany(p => p.HsCourses)
                .HasForeignKey(d => d.CourSubjUid)
                .HasConstraintName("FK_hs_course_hs_subject");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HsCourse> entity);
    }
}
