// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Homeschool.Data;
using Homeschool.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Homeschool.Data.Context.Configurations
{
    public partial class HsGradebookConfiguration : IEntityTypeConfiguration<HsGradebook>
    {
        public void Configure(EntityTypeBuilder<HsGradebook> entity)
        {
            entity.Property(e => e.GradUid).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HsGradebook> entity);
    }
}
