// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Homeschool.Data;
using Homeschool.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Homeschool.Data.Context.Configurations
{
    public partial class HsLessonConfiguration : IEntityTypeConfiguration<HsLesson>
    {
        public void Configure(EntityTypeBuilder<HsLesson> entity)
        {
            entity.Property(e => e.LessUid).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.LessChapU)
                .WithMany(p => p.HsLessons)
                .HasForeignKey(d => d.LessChapUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_hs_lesson_hs_chapter");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HsLesson> entity);
    }
}
